### ISSUE TITLE
Support for dhcp relay on MX vlans

### ISSUE THREAD

**Issue by thomasnoppe** [CiscoDevNet/terraform-provider-meraki#23]
Hi,

Thank you for building this Terraform provider.
I am however missing some features, I will create an issue per feature request.

This one is to be able to configure the dhcp relay servers on a vlan on a MX.
Our dhcp servers are only reachable over site-to-site so a seperate resource would be great.
Then I dont have cyclic dependencies between the vlan and dhcp relay and site-to-site vpn (you can only configure a dhcp relay if there is a route to it and if you dont have site-to-site yet because you need to configure the vlans first there would be cyclic dependency).

kind regards

**Comment by danischm** [comment]
Hi @thomasnoppe, thanks for opening this issue! It looks like the reason the DHCP relay configuration is missing from the existing resource is due to an error in the OpenAPI specification. We will correct this and enhance the existing `meraki_appliance_vlan` resource to support those additional attributes. Nevertheless, from what I understand, this would not solve your issue, as you would need to configure the DHCP relay part independently of the remaining configuration due to some other configuration that needs to be applied as a pre-requisite, which itself depends on the base vlan configuration. Is that the correct understanding?

**Comment by danischm** [comment]
https://github.com/CiscoDevNet/terraform-provider-meraki/commit/f00c6be51ee82a288675126ff96eea2c6aee20db

**Comment by thomasnoppe** [comment]
> Hi @thomasnoppe, thanks for opening this issue! It looks like the reason the DHCP relay configuration is missing from the existing resource is due to an error in the OpenAPI specification. We will correct this and enhance the existing `meraki_appliance_vlan` resource to support those additional attributes. Nevertheless, from what I understand, this would not solve your issue, as you would need to configure the DHCP relay part independently of the remaining configuration due to some other configuration that needs to be applied as a pre-requisite, which itself depends on the base vlan configuration. Is that the correct understanding?

Yes you are correct!

**Comment by danischm** [comment]
Enhanced existing resource and added a new resource in v0.1.3 release.
